name: Test and Lint on Push and PR

on: [push, pull_request]

jobs:
  test:
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        python:
          - 2.7
          - 3.4
          - 3.5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
          with:
            python-version: "${{matrix.python}}"
      - run: pip install -r requirements.txt
      - run: nosetests